### PR TITLE
WIP Infrastructure update

### PR DESCRIPTION
**Pull request by bsipocz**
Including:

 -   updating ``astropy-helpers`` to 1.0.5
 -   opting in ``ci-helpers`` with travis
 -   fixing docs warnings to make sphinx build pass
 -   copying over a few missing things from the package template (conftest, tests directory setup)

### CODE REVIEW

**Comment by bsipocz** [comment]
@keflavich - I seems like that travis is not running on ``gaussfitter`` yet. Could you switch it on?

**Comment by keflavich** [comment]
Thanks for catching that.  Done.

**Comment by bsipocz** [comment]
@keflavich - This is ready now.

**Comment by keflavich** [comment]
Thanks!

**Pull request merged**
